version: '3'
services:
    microexp:
        build: ./micrometer-experiment/. 
        container_name: microexp
        ports:
            - 8080:8080
            - 9010:9010
        networks:
            testing_net:
                ipv4_address: 172.28.1.1

    jmxcollector:
        build: ./jmxcollector/.
        container_name: jmxcollector
        depends_on:
            - microexp
            - graphite
        networks:
            testing_net:
                ipv4_address: 172.28.1.2

    graphite:
        container_name: graphite
        image: "graphiteapp/graphite-statsd"
        ports:
            - 80:80
            - 2003-2004:2003-2004
            - 2023-2024:2023-2024
            - 8125:8125/udp
            - 8126:8126
        networks:
            testing_net:
                ipv4_address: 172.28.1.3

networks:
    testing_net:
        ipam:
            driver: default 
            config:
                - subnet: 172.28.0.0/16
